### ISSUE TITLE
Meta data ignored if datakeys dynamic

### ISSUE THREAD

**Issue by ludwik** [joegallo/doric#3]
Hi.

``` clojure
(ns myns
  (:require [doric.core :only [table csv html org raw] :as dor])

(defn dortest1 [datakeys tabledata]
  (dor/table ^{:format dor/html} datakeys tabledata))

(dortest1 [:a :b] [{:a 1 :b 2} {:a 3 :b 4}])
;;BAD, expecting html output
--> "|---+---|\n| A | B |\n|---+---|\n| 1 | 2 |\n| 3 | 4 |\n|---+---|"


(defn dortest2 [datakeys tabledata]
  (dor/table ^{:format dor/html} [:a :b] tabledata))

;;OK, but had to force the datakeys, which are now not dynamic
(dortest2 [:a :b] [{:a 1 :b 2} {:a 3 :b 4}])
--> "<table>\n<tr><th>A</th><th>B</th></tr>\n<tr><td>1</td><td>2</td></tr>\n<tr><td>3</td><td>4</td></tr>\n</table>"

```

**Comment by joegallo** [comment]
Yeah, that issue is the worst -- and one of the reasons I'm nuking the metadata for config in the next version.

**Comment by joegallo** [comment]
```
; CIDER 0.7.0 (Java 1.8.0_05, Clojure 1.5.1, nREPL 0.2.3, cider-nrepl 0.7.0)
user> (def a [1 2])
#'user/a
user> (defn print-meta [x] (println (meta x)))
#'user/print-meta
user> (print-meta ^{:z 1} a)
nil
nil
user> (print-meta ^{:z 1} [1 2])
{:z 1}
nil
user> (print-meta (with-meta [1 2] {:z 1}))
{:z 1}
nil
user> (print-meta (with-meta a {:z 1}))
{:z 1}
nil
```

See the above -- it's just how clojure works, sadly, nothing special about how doric happens to be doing things.

That said, it's lame, and if I had known that this would be result of using metadata to convey the extra info, I never would have added that option. It's gross.

The next version will remove that, because it just ends up being surprising and frustrating.

**Comment by joegallo** [comment]
That said, I've been sitting on the third-argument-map-as-config code for a long while, so I'll knock it into shape and get it released sometime today or tomorrow.

**Comment by joegallo** [comment]
Alrighty, 0.9.0 is deployed to clojars. It removes the ability to use metadata for table config, so just remove that ^ character and you'll be passing the config info as an ordinary map and everything should work as you expect.

Thanks for bringing this up! Let me know if there's anything else you need from doric.

**Comment by ludwik** [comment]
Thank you!
